/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddRecord: typeof import('./components/AddRecord.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RemoveRecord: typeof import('./components/RemoveRecord.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UpdateRecord: typeof import('./components/UpdateRecord.vue')['default']
  }
}
