/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/Database': RouteRecordInfo<'/Database', '/Database', Record<never, never>, Record<never, never>>,
    '/Directory': RouteRecordInfo<'/Directory', '/Directory', Record<never, never>, Record<never, never>>,
    '/Operation': RouteRecordInfo<'/Operation', '/Operation', Record<never, never>, Record<never, never>>,
  }
}
